#!/bin/sh

main() {
	git pull --rebase --prune
	git submodule update --init --recursive
	git submodule update --remote --merge

	for home in "asounrc" "gitconfig" "mpd" "ncmpcpp" "tmux.conf" \
		    "xinitrc" "zlogin" "zprofile" "zsh" "zshenv" "zshrc"; do
		cp -rv "$(dirname "$0")/.$home" "$HOME"
	done

	for xdg in "nvim" "picom" "setxkbmap" "vifm"; do
		cp -rv "$(dirname "$0")/.config/$xdg" "$HOME/.config/"
	done
}

main "$@"
