#!/usr/bin/env bash

CONFIG_HOME=(asoundrc fonts gitconfig mpd ncmpcpp tmux.conf zlogin zsh zshenv zshrc)
XDG_CONFIG_HOME=(picom fontconfig nvim vifm)
REPO_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)

usage() {
cat << EOF
Usage: install [commands]

Commands:
clean    - remove all created symlinks
conflict - list conflicted directory
dotfiles - install all config files
git      - install git config files only
help     - show information about the commands
EOF
}

setup-dotfiles() {
	for h in ${CONFIG_HOME[@]}; do
		if [[ ! -f $HOME/.$h ]]; then
			ln -sf $REPO_PATH/.$h $HOME
		fi
	done

	if [[ -d $HOME/.zsh/vendor/fzf ]]; then
		echo 'entering: ~/.zsh/vendor/fzf'
		cd $HOME/.zsh/vendor/fzf
		./install --bin --no-key-bindings --no-completion --no-update-rc --no-bash --no-zsh --no-fish --64
		echo -e 'leaving: ~/.zsh/vendor/fzf\n'
		cd $REPO_PATH
	fi
	
	for c in ${XDG_CONFIG_HOME[@]}; do
		if [[ ! -f $HOME/.config/$c ]]; then
			ln -sf $REPO_PATH/.config/$c $HOME/.config
		fi
	done
}

clean-symlink() {
	for h in ${CONFIG_HOME[@]}; do
		if [[ -L $HOME/.$h ]]; then
			rm -f $HOME/.$h
		fi
	done
	
	for c in ${XDG_CONFIG_HOME[@]}; do
		if [[ -L $HOME/.config/$c ]]; then
			rm -f $HOME/.config/$c
		fi
	done
	
	rm -f $HOME/.*.zwc*
}

setup-git() {
	ln -sf $REPO_PATH/.gitconfig $HOME
	printf "Username for 'https://github.com': "
	read name
	printf "Email for 'https://$name@github.com': "
	read email
	
	git config --file "$HOME/.gitconfig.local" user.name "$name"
	git config --file "$HOME/.gitconfig.local" user.email "$email"
}

check-conflict() {
echo "Conflicted Directories:"
	for h in ${CONFIG_HOME[@]}; do
		if [[ -d $HOME/.$h && -L $HOME/.$h ]]; then
			echo "$HOME/.$h"
		fi
	done
	
	for c in ${XDG_CONFIG_HOME[@]}; do
		if [[ -d $HOME/.config/$c && -L $HOME/.config/$c ]]; then
			echo "$HOME/.config/$c"
		fi
	done
}

main() {
	if [[ ! -d $HOME/.config ]]; then
		mkdir $HOME/.config
	fi

	case "$1" in
		help)
			usage
			;;
		git)
			setup-git
			;;
		dotfiles)
			setup-dotfiles
			;;
		clean)
			clean-symlink
			;;
		conflict)
			check-conflict
			;;
		"")
			usage
			;;
		*)
			usage
			echo
			echo "error: unrecognized options: $1"
			;;
	esac
}

main "$@"
